### ISSUE TITLE
physical link activations not pushing into HASS

### ISSUE THREAD

**Issue by bbrendon** [gwww/hass-upb#6]
This morning when waking up and also when leaving the house, HASS was not in sync with the lights. 

I think the link activation from physical button presses aren't being reflected in HASS.

I don't have a lot of testing or information on this yet, but something is fishy. More to come.

**Comment by tdejneka** [comment]
I have to admit that all my testing has been limited to fairly short sessions (< 2 hours) because I'm running it on a test instance of Home Assistant (Core) on a laptop. This test system isn't on all day. During those (comparatively short) test periods, I've tested physical button presses and the UPB integration had updated all affected entities. Perhaps I should leave the test system running for a few days and see if it reproduces "something is fishy". :)

**Comment by gwww** [comment]
I have a suspicion that the proto code is not quite right. Pretty sure I dropped the `busy` timer to low. I'm investigating the whole protocol layer and how it can be better.

**Comment by bbrendon** [comment]
I did some testing when I got home in two rooms and didn't notice the problem. I'm too lazy right now to test the more complex shutdown links. More to come :)

**Comment by gwww** [comment]
Test with 0.0.9-alpha. Timer upped from .25 to .75 when a BUSY is received. Seems stable there.

**Comment by bbrendon** [comment]
0.0.9 didn't do it. The link turns off all the lights in the house with a fade rate of about 60 seconds. (didn't check, but something like that).

The log of the button press is below. I'm not sure why it's talking about a lamp in the log. Ahhhh.... So I tested it again. It seems that one lamp listed below is one of about 35 things that gets updated in hass. Everything else seems to not update.

```
2020-02-04 17:39:46 DEBUG (MainThread) [upb_lib.proto] message received:     update 'PU890C16630F20FFFFC5'
2020-02-04 17:39:46 DEBUG (MainThread) [upb_lib.links] Activate BedMaster-Button4 22_99
2020-02-04 17:39:46 DEBUG (MainThread) [upb_lib.links]   Updating 'LivingRm Lamp1' to dim level 0
2020-02-04 17:39:46 DEBUG (MainThread) [upb_lib.proto] message received:     update 'PU890D16630F20FFFFC4'
2020-02-04 17:39:46 DEBUG (MainThread) [upb_lib.message] Repeated message!!!
2020-02-04 17:39:47 DEBUG (MainThread) [upb_lib.proto] message received:     update 'PU890E16630F20FFFFC3'
2020-02-04 17:39:47 DEBUG (MainThread) [upb_lib.message] Repeated message!!!
2020-02-04 17:39:47 DEBUG (MainThread) [upb_lib.proto] message received:     update 'PU890F16630F20FFFFC2'
2020-02-04 17:39:47 DEBUG (MainThread) [upb_lib.message] Repeated message!!!
2020-02-04 17:40:01 DEBUG (MainThread) [upb_lib.proto] message received:   accepted 'PA'
2020-02-04 17:40:01 DEBUG (MainThread) [upb_lib.proto] message received:       nack 'PN'
```

**Comment by gwww** [comment]
Not following you. `BedMaster-Button4` is the scene button pressed. It seems to have just one light associated with that scene, `LivingRm Lamp1`. It looks like that link cause the lamp to turn off.

The only other thing I see in the log you sent is that when the button is pressed the ACTIVATE message is sent 4 times. Seems like a lot to me.

So what is not working that you expect to work? Are those switches configured to transmit on button press?

**Comment by gwww** [comment]
A couple more points. My fix with the busy timer is making sending messages from hass more reliable. It sounds like you are having problems with hass receiving messages.

Maybe the transmitting of messages 4 times is causing other messages on the powerline to get dropped?

**Comment by bbrendon** [comment]
Ooooops. It seems I need to go back to the drawing board. After some digging it seems like it's working properly but I have no idea how this was working previously. I'll be back when I finish digging through my cluster-F.

**Comment by bbrendon** [comment]
Okay. Closing. All figured out. I my UPB buttons are links with one device (upstart won't let you have 0 devices) so they can just be treated as a button that calls a script.

The button was triggering my old link scripts so it was half working.  It wasn't calling your new  turn_on/scene.  So the lights went off without telling HASS.  OBVIOUSLY/not obviously!

**Comment by gwww** [comment]
If you really just want a button that does activate etc you could link it to a non-existent device. That would be enough to trick out UPStart and you would have your automation button.

**Comment by tdejneka** [comment]
I have a scene (UPB Link), defined in UPStart, that has no linked devices. A button has been programmed to activate/deactivate this scene. It serves as a signal to run an automation.


In this screenshot from UPStart, device 001's button 3 has been programmed to activate scene 8 (link 8). None of the UPB devices are linked to this scene. Scene 8 is named Tablelamp because it serves as a signal to control an X10 lamp (via the automation).

![Annotation 2020-02-04 224351](https://user-images.githubusercontent.com/44732909/73809304-d90bf380-47a0-11ea-8870-b272af948e51.png)
